<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="generator" content="Asciidoctor 2.0.15"><title>Railroad Oriented Programming in C#</title><link rel="stylesheet" href="/blog/rop-cs.1dc85963.css"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.3/styles/solarized-light.min.css"><base target="_parent"></head><body class="article"> <div id="header"> <h1>Railroad Oriented Programming in C#</h1> </div> <div id="content"> <div class="sect1"> <h2 id="_the_problem_implicit_function_failure">The problem: implicit function failure</h2> <div class="sectionbody"> <div class="paragraph"> <p>Functions are often designed for the <strong>success path</strong>: the return type only consists of the type the function will return in case of a successful execution. The following function definition likely wouldn&#8217;t stand out in an average code base.</p> </div> <div class="listingblock"> <div class="content"> <pre class="highlight highlightjs"><code class="hljs language-cs" data-lang="cs">string GetEmailAddress(string username)
{
  // ...
}</code></pre> </div> </div> <div class="paragraph"> <p>This function is supposed to return an email address for a user with the username that is passed into the function. If the function isn&#8217;t able to meet this expectation, e.g. because the user doesn&#8217;t exist, or it has no email address defined, usually one of the following things happens.</p> </div> <div class="arabic olist"> <ol class="arabic"> <li> <p>A default value is returned, such as a null reference.</p> </li> <li> <p>An exception is thrown.</p> </li> </ol> </div> <div class="imageblock kroki"> <div class="content"> <svg xmlns="http://www.w3.org/2000/svg" class="pikchr" width="507" height="164" viewbox="0 0 634.745 205.013"> <path d="M38,74L110,74A36 36 0 0 0 146 38A36 36 0 0 0 110 2L38,2A36 36 0 0 0 2 38A36 36 0 0 0 38 74Z" style="fill:none;stroke-width:2.16;stroke:#000"></path> <text x="74" y="38" text-anchor="middle" fill="rgb(0,0,0)" dominant-baseline="central">username</text> <polygon points="218,38 206,42 206,33" style="fill:#000"></polygon> <path d="M146,38L212,38" style="fill:none;stroke-width:2.16;stroke:#000"></path> <path d="M218,74L416,74L416,2L218,2Z" style="fill:none;stroke-width:2.16;stroke:#000"></path> <text x="317" y="38" text-anchor="middle" fill="rgb(0,0,0)" dominant-baseline="central">GetEmailAddress</text> <polygon points="488,38 477,42 477,33" style="fill:#000"></polygon> <path d="M416,38L482,38" style="fill:none;stroke-width:2.16;stroke:#000"></path> <path d="M524,74L596,74A36 36 0 0 0 632 38A36 36 0 0 0 596 2L524,2A36 36 0 0 0 488 38A36 36 0 0 0 524 74Z" style="fill:#add8e6;stroke-width:2.16;stroke:#000"></path> <text x="560" y="38" text-anchor="middle" fill="rgb(0,0,0)" dominant-baseline="central">email address</text> <polygon points="317,130 313,119 321,119" style="fill:#000"></polygon> <path d="M317,74L317,125" style="fill:none;stroke-width:2.16;stroke:#000"></path> <path d="M281,202L353,202A36 36 0 0 0 389 166A36 36 0 0 0 353 130L281,130A36 36 0 0 0 245 166A36 36 0 0 0 281 202Z" style="fill:#dc143c;stroke-width:2.16;stroke:#000"></path> <text x="317" y="166" text-anchor="middle" fill="rgb(0,0,0)" dominant-baseline="central">?</text> </svg> </div> </div> <div class="sect2"> <h3 id="_problems_with_using_default_values_for_failure">Problems with using default values for failure</h3> <div class="ulist"> <ul> <li> <p>For <strong>value types</strong> the default value is a valid member of the value space of the type. So there would be no way to distinguish between a success return value and a failure return value in this case.</p> </li> <li> <p>For <strong>reference types</strong> the default value is not a valid member of the value space. However, null references have their own set of problems. (Since the addition of nonnullable reference types in C# 8.0 this set of problems has been diminished a great deal, but a non-negligible pool of pitfalls remains.)</p> </li> <li> <p>There is no way to return any data along with the failure, such as an error message or some object indicating the reason or nature of the failure.</p> </li> </ul> </div> </div> <div class="sect2"> <h3 id="_problems_with_using_exceptions_for_failure">Problems with using exceptions for failure</h3> <div class="ulist"> <ul> <li> <p>Exceptions are not part of the function signature. As such a caller of a function does not know which exceptions to catch unless he reads all the code that is possibly hit by the function, assuming that he even has access to it.</p> </li> <li> <p>In well-defined and well-maintained APIs the list of possible exceptions a function can throw is stated in the documentation. However:</p> <div class="ulist"> <ul> <li> <p>The user of the API can easily overlook exceptions without compiler warnings.</p> </li> <li> <p>If the API changes over time and adds more exceptions, the user will not be notified of this by the compiler, simply because the compiler doesn&#8217;t know anything about the exceptions a function can throw.</p> </li> <li> <p>Most functions are not part of a well-defined API.</p> </li> </ul> </div> </li> </ul> </div> </div> <div class="sect2"> <h3 id="_the_problem_of_implicit_failure_in_general">The problem of implicit failure in general</h3> <div class="paragraph"> <p>While the above paragraphs point out some problems with the respective failure-handling strategies, perhaps the biggest of all problems is this: the <strong>failure path</strong> of <code>GetEmailAddress</code> is <strong>implicitly defined</strong>. As such, it doesn&#8217;t get the same amount of attention as the success path and is, frankly, too often completely overlooked. This is not surprising, since either of the strategies leaves the compiler clueless and unable to help the programmer to write code that properly handles failures.</p> </div> </div> <div class="sect2"> <h3 id="_solution_explicit_failure">Solution: explicit failure</h3> <div class="paragraph"> <p>The solution is fairly straightforward: make the failure path part of the normal return type of the function.</p> </div> <div class="imageblock kroki"> <div class="content"> <svg xmlns="http://www.w3.org/2000/svg" class="pikchr" width="528" height="151" viewbox="0 0 660.94 189.706"> <path d="M38,130L110,130A36 36 0 0 0 146 94A36 36 0 0 0 110 58L38,58A36 36 0 0 0 2 94A36 36 0 0 0 38 130Z" style="fill:none;stroke-width:2.16;stroke:#000"></path> <text x="74" y="94" text-anchor="middle" fill="rgb(0,0,0)" dominant-baseline="central">username</text> <polygon points="218,94 206,99 206,90" style="fill:#000"></polygon> <path d="M146,94L212,94" style="fill:none;stroke-width:2.16;stroke:#000"></path> <path d="M218,130L416,130L416,58L218,58Z" style="fill:none;stroke-width:2.16;stroke:#000"></path> <text x="317" y="94" text-anchor="middle" fill="rgb(0,0,0)" dominant-baseline="central">GetEmailAddress</text> <path d="M550,74L622,74A36 36 0 0 0 658 38A36 36 0 0 0 622 2L550,2A36 36 0 0 0 514 38A36 36 0 0 0 550 74Z" style="fill:#add8e6;stroke-width:2.16;stroke:#000"></path> <text x="586" y="38" text-anchor="middle" fill="rgb(0,0,0)" dominant-baseline="central">email address</text> <path d="M550,187L622,187A36 36 0 0 0 658 151A36 36 0 0 0 622 115L550,115A36 36 0 0 0 514 151A36 36 0 0 0 550 187Z" style="fill:orange;stroke-width:2.16;stroke:#000"></path> <text x="586" y="151" text-anchor="middle" fill="rgb(0,0,0)" dominant-baseline="central">user not found</text> <polygon points="514,38 506,47 502,40" style="fill:#000"></polygon> <path d="M416,94L509,41" style="fill:none;stroke-width:2.16;stroke:#000"></path> <polygon points="514,151 502,149 506,142" style="fill:#000"></polygon> <path d="M416,94L509,148" style="fill:none;stroke-width:2.16;stroke:#000"></path> </svg> </div> </div> <div class="paragraph"> <p>This sounds trivial, so why isn&#8217;t this done traditionally? At least part of that has to do with the fact C-like languages do not make it easy to do this. You would need to have a return type that can be <em>either</em> the success type <em>or</em> the failure type. In functional programming languages such a construct <em>does</em> exist and is called a <a href="https://en.wikipedia.org/wiki/Tagged_union">Discriminated Union</a>. But C-like languages, including C#, do not have support for such a type. Luckily C# has had added lots of language features over the years that make it possible to emulate discriminated unions in a neat way. We will have a look at one way of implementing explicit failure in C#: a <code>Result</code> type with two subtypes, one for the success path and one for the failure path.</p> </div> </div> <div class="sect2"> <h3 id="_there_is_still_a_place_for_exceptions">There is still a place for exceptions</h3> <div class="paragraph"> <p>Making the failure path part of the function return type does not mean that there are no exceptional situations for which the exception throwing mechanism is a good fit. To give an extreme example, almost any function can <em>in theory</em> encounter an <code>OutOfMemoryException</code> while doing an allocation. Or any function could <em>in theory</em> contain a bug causing a <code>NullReferenceException</code> to be thrown. But this does not mean that we should write every function with that in mind, and have it be part of the normal failure path. These cases are really exceptions which are <strong>unexpected</strong>, and should not happen. There is often no proper way to handle them other than to cancel the whole "operation" and present the user with an appropriate error, indicating that something went completely sideways.</p> </div> <div class="paragraph"> <p>A good way for deciding whether to propagate a failure by throwing an exception is by asking the following question. <em>Would the exeption be handled with no error-specific logic and should it cause the entire operation that is being done to be aborted</em>? If the answer is yes, then it is probably appropriate to let the failure be handled by throwing an exception and catch it up the callchain at the "edge of the operation".</p> </div> <div class="paragraph"> <p>What the scope of that "operation" should be is completely context dependent. For instance, in a web application that could be the http request. In other contexts, like a CLI progam, it could be the whole process. Again, note that the edges of the code that constitutes an "operation" should have appropriate try/catch clauses.</p> </div> <div class="paragraph"> <p>Tldr, exceptions should not be dealt with on a function level but rather on an "operation" level, and they are really <strong>exceptional</strong>.</p> </div> </div> </div> </div> <div class="sect1"> <h2 id="_a_result_type_supporting_the_failure_path">A Result type supporting the failure path</h2> <div class="sectionbody"> <div class="paragraph"> <p>While C# does not directory support Discriminated Unions, it does support subclassing. Since a class can have multiple subclasses, and any object is always just one of them, we can use this phenomenon to implement the notion of having two returntypes, one for success result, and one for the failure result.</p> </div> <div class="listingblock"> <div class="content"> <pre class="highlight highlightjs"><code class="hljs language-cs" data-lang="cs">public abstract class Result {
  public class Success : Result { }
  public class Failure : Result { }
  // Private constructor so we are certain that Success and Failure are the only subclasses
  private Result () { }
}</code></pre> </div> </div> <div class="paragraph"> <p>However, this class does not allow us to associate any return data with either the success or the failure result. We can fix that.</p> </div> <div class="listingblock"> <div class="content"> <pre class="highlight highlightjs"><code class="hljs language-cs" data-lang="cs">public abstract class Result&lt;TResult, TError&gt; {
  public sealed class Success : Result&lt;TResult, TError&gt; {
    public readonly TResult ResultValue;
    public Success(TResult result){
      ResultValue = result;
    }
  }
  public sealed class Failure : Result&lt;TResult, TError&gt; {
    public readonly TError ErrorValue;
    public Failure(TError error){
      ErrorValue = error;
    }
  }
  // Private constructor so we are certain that Success and Failure are the only subclasses
  private Result () { }
}</code></pre> </div> </div> <div class="paragraph"> <p>With this in our toolkit we can now implement our <code>GetEmailAddress</code> function from earlier with an explicit failure path.</p> </div> <div class="listingblock"> <div class="content"> <pre class="highlight highlightjs"><code class="hljs language-cs" data-lang="cs">Result&lt;string, string&gt; GetEmailAddress(string username)
{
  var user = GetUser(username);
  if (user != null) {
    var email = user.Email;
    if (!string.IsNullOrEmpty(email))
    {
      return new Success(email);
    }
    return new Failure("User has no email");
  }
  return new Failure("User does not exist");
}</code></pre> </div> </div> <div class="paragraph"> <p>Usage of this function would look something like</p> </div> <div class="listingblock"> <div class="content"> <pre class="highlight highlightjs"><code class="hljs language-cs" data-lang="cs">var result = GetEmailAddress(username);
if (result is Result&lt;string,string&gt;.Success) {
  var email = ((Result&lt;string,string&gt;.Success)result).ResultValue;
  // Do what you wanna do
} else {
  var error = ((Result&lt;string,string&gt;.Failure)result).ErrorValue;
  // Handle the failure appropriately
}</code></pre> </div> </div> <div class="paragraph"> <p>As you can see we&#8217;ve achieved an explicit failure path. But the code leaves much to be desired. Even more so when we need to call more than one function.</p> </div> <div class="listingblock"> <div class="content"> <pre class="highlight highlightjs"><code class="hljs language-cs" data-lang="cs">Result&lt;EmailMessage, string&gt; CreateEmailMessage(string emailaddress) { ... }

// ...

var result = GetEmailAddress(username);
if (result is Result&lt;string,string&gt;.Success) {
  var email = ((Result&lt;string,string&gt;.Success)result).ResultValue;
  var result2 = CreateEmailMessage(email);
  if (result2 is Result&lt;EmailMessage,string&gt;.Success) {
    var message = ((Result&lt;EmailMessage,string&gt;.Success)result2).ResultValue;
    // And so on...
  } else {
    var error2 = ((Result&lt;EmailMessage,string&gt;.Failure)result).ErrorValue;
    // Handle the failure appropriately
  }
} else {
  var error = ((Result&lt;string,string&gt;.Failure)result).ErrorValue;
  // Handle the failure appropriately
}</code></pre> </div> </div> <div class="paragraph"> <p>We would like to</p> </div> <div class="ulist"> <ul> <li> <p>not have to unwrap the result type by doing a type check + cast</p> </li> <li> <p>not have a new nesting level for each subsequent function we call</p> </li> </ul> </div> </div> </div> <div class="sect1"> <h2 id="_a_result_type_supporting_railroad_oriented_programming">A Result type supporting Railroad Oriented Programming</h2> <div class="sectionbody"> <div class="paragraph"> <p>To resolve the complaints about our previous implementation, we&#8217;ll define an <code>OnSuccess</code> function and a <code>Handle</code> function. They will do the unwrapping for us and form a <a href="https://en.wikipedia.org/wiki/Fluent_interface">Fluent Interface</a> and thereby removing the nesting.</p> </div> <div class="listingblock"> <div class="content"> <pre class="highlight highlightjs"><code class="hljs language-cs" data-lang="cs">public abstract class Result&lt;TResult, TError&gt; {

  public abstract Result&lt;TNextResult, TError&gt; OnSuccess&lt;TNextResult&gt;(
    Func&lt;TResult, Result&lt;TNextResult, TError&gt;&gt; onSuccess);
  public abstract TReturn Handle&lt;TReturn&gt;(
    Func&lt;TResult, TReturn&gt; onSuccess, Func&lt;TError, TReturn&gt; onFailure);

  public sealed class Success : Result&lt;TResult, TError&gt; {

    public readonly TResult ResultValue;
    public Success(TResult result){
      Result = result;
    }

    public override Result&lt;TNextResult, TError&gt; OnSuccess&lt;TNextResult&gt;(
      Func&lt;TResult, Result&lt;TNextResult, TError&gt;&gt; onSuccess) =&gt; onSuccess(ResultValue);
    public override TReturn Handle&lt;TReturn&gt;(
      Func&lt;TResult, TReturn&gt; onSuccess, Func&lt;TError, TReturn&gt; onFailure) =&gt; onSuccess(ResultValue);
  }

  public sealed class Failure : Result&lt;TResult, TError&gt; {

    public readonly TError ErrorValue;
    public Failure(TError error){
      ErrorValue = error;
    }

    public override Result&lt;TNextResult, TError&gt; OnSuccess&lt;TNextResult&gt;(
      Func&lt;TResult, Result&lt;TNextResult, TError&gt;&gt; onSuccess) =&gt; new Failure(ErrorValue);
    public override TReturn Handle&lt;TReturn&gt;(
      Func&lt;TResult, TReturn&gt; onSuccess, Func&lt;TError, TReturn&gt; onFailure) =&gt; onFailure(Error);
  }
  private Result () { }
}</code></pre> </div> </div> <div class="paragraph"> <p>Apart from the daunting function signatures, the actual function bodies are trivial. Yet they suddenly allow us to write very concise code. Compare the following with what we had in the previous section.</p> </div> <div class="listingblock"> <div class="content"> <pre class="highlight highlightjs"><code class="hljs language-cs" data-lang="cs">var result = GetEmailAddress(username)
  .OnSuccess(email =&gt; CreateEmailMessage(email));
  .Handle(
    message =&gt; ...,
    error =&gt; ...
  );</code></pre> </div> </div> </div> </div> </div> <div id="footer"> <div id="footer-text"> Last updated 2021-07-15 19:10:59 +0200 </div> </div> <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.3/highlight.min.js"></script> <script>hljs.initHighlighting.called||(hljs.initHighlighting.called=!0,[].slice.call(document.querySelectorAll("pre.highlight > code")).forEach((function(l){hljs.highlightBlock(l)})));</script> </body></html>